// 2025 JUPAS 收生分數數據
// 資料來源：Obsidian vault ~/obsidian/hkdse/

export const universities = [
  { id: 'cityu', name: '香港城市大學', name_en: 'CityU', color: '#3b82f6', note: '' },
  { id: 'hkbu', name: '香港浸會大學', name_en: 'HKBU', color: '#f97316', note: '' },
  { id: 'hkust', name: '香港科技大學', name_en: 'HKUST', color: '#22c55e', note: '' },
  { id: 'hku', name: '香港大學', name_en: 'HKU', color: '#ef4444', note: '' },
  { id: 'polyu', name: '香港理工大學', name_en: 'PolyU', color: '#a855f7', note: '' },
  { id: 'hkmud', name: '香港都會大學', name_en: 'HKMU', color: '#06b6d4', note: '' },
]

export const categories = [
  '全部', '健康醫學', '商科', '工程', '理科', '電腦/數據',
  '文科', '社科', '創意', '法學', '教育', '建築', '傳播', '雙學位'
]

// HKDSE grade to point mapping (2025+)
export const gradePoints = {
  '5**': 8.5, '5*': 7, '5': 5.5,
  '4': 4, '3': 3, '2': 2, '1': 1,
  'Attained': 0, '-': 0, '': 0, null: 0
}

export const gradeOptions = ['', '5**', '5*', '5', '4', '3', '2', '1', 'Attained']

export const programs = [
  // ===== CityU =====
  { uni: 'cityu', code: 'JS1211', name: '生物醫學工程', formula: '最佳5科', median: 39, lq: 38, category: '健康醫學' },
  { uni: 'cityu', code: 'JS1001', name: '工商管理（全球商務）', formula: '最佳5科', median: 29.5, lq: 28, category: '商科' },
  { uni: 'cityu', code: 'JS1002', name: '工商管理（會計）', formula: '最佳5科', median: 22, lq: 21.5, category: '商科' },
  { uni: 'cityu', code: 'JS1005', name: '工商管理（管理學）', formula: '最佳5科', median: 22, lq: 21.5, category: '商科' },
  { uni: 'cityu', code: 'JS1007', name: '工商管理（市場學）', formula: '最佳5科', median: 24.5, lq: 23.5, category: '商科' },
  { uni: 'cityu', code: 'JS1012', name: '經濟及金融', formula: '最佳5科', median: 23, lq: 22.5, category: '商科' },
  { uni: 'cityu', code: 'JS1013', name: '工商管理（商業經濟學）', formula: '最佳5科', median: 22, lq: 21.5, category: '商科' },
  { uni: 'cityu', code: 'JS1014', name: '工商管理（金融學）', formula: '最佳5科', median: 21.5, lq: 21.5, category: '商科' },
  { uni: 'cityu', code: 'JS1017', name: '智能信息系統', formula: '最佳5科', median: 21, lq: 20.5, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1018', name: '環球商業系統管理', formula: '最佳5科', median: 24, lq: 23.5, category: '商科' },
  { uni: 'cityu', code: 'JS1070', name: '人工智能、計算及轉型（ACT）', formula: '3核心+2選修', median: 31, lq: 30, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1071', name: '數據科學', formula: '3核心+2選修', median: 27.5, lq: 27.5, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1072', name: '數據科學（理學）', formula: '3核心+2選修', median: 29, lq: 28.5, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1074', name: '數據及系統工程', formula: '3核心+2選修', median: 28, lq: 27.5, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1204', name: '電腦科學', formula: '最佳5科', median: 23, lq: 22, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1218', name: '網絡安全', formula: '最佳5科', median: 20.5, lq: 20.5, category: '電腦/數據' },
  { uni: 'cityu', code: 'JS1201', name: '建築及土木工程', formula: '最佳5科', median: 43.5, lq: 42.5, category: '工程' },
  { uni: 'cityu', code: 'JS1210', name: '材料科學及工程', formula: '最佳5科', median: 34, lq: 32.5, category: '工程' },
  { uni: 'cityu', code: 'JS1216', name: '智能製造工程', formula: '最佳5科', median: 20, lq: 18, category: '工程' },
  { uni: 'cityu', code: 'JS1217', name: '工程研究創新及跨學科（PRIME）', formula: '最佳5科', median: 38.5, lq: 38, category: '工程' },
  { uni: 'cityu', code: 'JS1219', name: '創新及企業工程', formula: '最佳5科', median: 19.5, lq: 18.5, category: '工程' },
  { uni: 'cityu', code: 'JS1102', name: '國際事務及全球事務', formula: '最佳5科', median: 24, lq: 23.5, category: '社科' },
  { uni: 'cityu', code: 'JS1109', name: '語言學及語言應用', formula: '3核心+2選修', median: 30, lq: 29.5, category: '文科' },
  { uni: 'cityu', code: 'JS1111', name: '犯罪學', formula: '最佳4科', median: 23, lq: 23, category: '社科' },
  { uni: 'cityu', code: 'JS1112', name: '心理學', formula: '最佳4科', median: 24.5, lq: 24, category: '社科' },
  { uni: 'cityu', code: 'JS1113', name: '社會工作', formula: '最佳4科', median: 23, lq: 23, category: '社科' },
  { uni: 'cityu', code: 'JS1200', name: '全球科研充實及科技創業（GREAT）', formula: '最佳4科', median: 37, lq: 36.5, category: '理科' },
  { uni: 'cityu', code: 'JS1202', name: '化學', formula: '最佳4科', median: 27.5, lq: 27, category: '理科' },
  { uni: 'cityu', code: 'JS1040', name: '創意藝術及科技（CREATE）', formula: '最佳5科', median: 28, lq: 24.5, category: '創意' },
  { uni: 'cityu', code: 'JS1041', name: '創意媒體', formula: '最佳5科', median: 25.5, lq: 25, category: '創意' },
  { uni: 'cityu', code: 'JS1042', name: '創意媒體（文學）', formula: '最佳5科', median: 27.5, lq: 27, category: '創意' },
  { uni: 'cityu', code: 'JS1043', name: '創意媒體（理學）', formula: '最佳5科', median: 26.5, lq: 25.5, category: '創意' },
  { uni: 'cityu', code: 'JS1044', name: '新媒體', formula: '最佳5科', median: 24, lq: 24, category: '創意' },
  { uni: 'cityu', code: 'JS1061', name: '法學士', formula: '最佳5科', median: 23, lq: 21.5, category: '法學' },
  { uni: 'cityu', code: 'JS1052', name: '環境科學工程及工商管理（金融）雙學位', formula: '最佳5科', median: 40, lq: 39.5, category: '雙學位' },
  { uni: 'cityu', code: 'JS1062', name: '法學士及工商管理（會計）雙學位', formula: '最佳5科', median: 29, lq: 25, category: '雙學位' },
  { uni: 'cityu', code: 'JS1123', name: '犯罪學及法學士雙學位', formula: '最佳5科', median: 24.5, lq: 23, category: '雙學位' },
  { uni: 'cityu', code: 'JS1221', name: '電腦科學及計算金融雙學位', formula: '最佳5科', median: 23, lq: 22, category: '雙學位' },

  // ===== HKBU =====
  { uni: 'hkbu', code: 'JS2020', name: '文學（中文/創意寫作/英文/人文/翻譯）', formula: '最佳5科', median: 21.95, lq: null, category: '文科' },
  { uni: 'hkbu', code: 'JS2025', name: '宗教、哲學與倫理', formula: '最佳5科', median: 21, lq: null, category: '文科' },
  { uni: 'hkbu', code: 'JS2060', name: '文學/音樂（音樂/創意產業）', formula: '最佳5科', median: 20.68, lq: null, category: '創意' },
  { uni: 'hkbu', code: 'JS2110', name: '工商管理（會計）', formula: '最佳5科', median: 22.15, lq: null, category: '商科' },
  { uni: 'hkbu', code: 'JS2120', name: '工商管理', formula: '最佳5科', median: 22.07, lq: null, category: '商科' },
  { uni: 'hkbu', code: 'JS2310', name: '傳播（新聞/公關廣告）', formula: '最佳5科', median: 22.99, lq: null, category: '傳播' },
  { uni: 'hkbu', code: 'JS2330', name: '電影與電視', formula: '最佳5科', median: 21.83, lq: null, category: '創意' },

  // ===== HKUST =====
  { uni: 'hkust', code: 'JS5101', name: '國際科研充實', formula: '最佳5科+加分', median: 38.25, lq: 37.88, category: '理科' },
  { uni: 'hkust', code: 'JS5102', name: '理學（A組）', formula: '最佳5科+加分', median: 33.13, lq: 32.63, category: '理科' },
  { uni: 'hkust', code: 'JS5103', name: '理學（B組）', formula: '最佳5科+加分', median: 33.38, lq: 32.75, category: '理科' },
  { uni: 'hkust', code: 'JS5118', name: '生物醫學及健康科學', formula: '最佳5科+加分', median: 43.13, lq: 40.50, category: '健康醫學' },
  { uni: 'hkust', code: 'JS5181', name: '理學（A組）附人工智能', formula: '最佳5科+加分', median: 37.50, lq: 36.00, category: '理科' },
  { uni: 'hkust', code: 'JS5212', name: '電腦工程', formula: '最佳5科+加分', median: 43.49, lq: 41.97, category: '工程' },
  { uni: 'hkust', code: 'JS5220', name: '化學及生物工程', formula: '最佳5科+加分', median: 41.49, lq: 39.59, category: '工程' },
  { uni: 'hkust', code: 'JS5230', name: '土木及環境工程', formula: '最佳5科+加分', median: 39.70, lq: 38.20, category: '工程' },
  { uni: 'hkust', code: 'JS5240', name: '電腦科學及工程', formula: '最佳5科+加分', median: 48.45, lq: 46.45, category: '工程' },
  { uni: 'hkust', code: 'JS5711', name: '創新、設計及科技', formula: '最佳5科+加分', median: 36.36, lq: 34.72, category: '工程' },
  { uni: 'hkust', code: 'JS5812', name: '環境管理及科技', formula: '最佳5科+加分', median: 32.50, lq: 31.05, category: '理科' },
  { uni: 'hkust', code: 'JS5901', name: '工程與工商管理雙學位', formula: '最佳5科+加分', median: 62.48, lq: 60.23, category: '雙學位' },
  { uni: 'hkust', code: 'JS5811', name: '生物科技及商業', formula: '最佳5科+加分', median: 38.63, lq: 36.56, category: '商科' },
  { uni: 'hkust', code: 'JS5813', name: '數學及經濟學', formula: '最佳5科+加分', median: 44.10, lq: 39.20, category: '理科' },
  { uni: 'hkust', code: 'JS5300', name: '商學及管理', formula: '最佳5科+加分', median: 35.00, lq: 33.90, category: '商科' },
  { uni: 'hkust', code: 'JS5311', name: '經濟學', formula: '最佳5科+加分', median: 36.55, lq: 35.40, category: '商科' },
  { uni: 'hkust', code: 'JS5312', name: '金融學', formula: '最佳5科+加分', median: 43.31, lq: 41.81, category: '商科' },
  { uni: 'hkust', code: 'JS5313', name: '環球商業', formula: '最佳5科+加分', median: 52.43, lq: 50.40, category: '商科' },
  { uni: 'hkust', code: 'JS5314', name: '資訊系統', formula: '最佳5科+加分', median: 35.93, lq: 35.40, category: '商科' },
  { uni: 'hkust', code: 'JS5315', name: '管理學', formula: '最佳5科+加分', median: 33.90, lq: 33.90, category: '商科' },
  { uni: 'hkust', code: 'JS5316', name: '市場學', formula: '最佳5科+加分', median: 32.55, lq: 32.40, category: '商科' },
  { uni: 'hkust', code: 'JS5317', name: '營運管理', formula: '最佳5科+加分', median: 32.40, lq: 32.05, category: '商科' },
  { uni: 'hkust', code: 'JS5318', name: '專業會計', formula: '最佳5科+加分', median: 34.05, lq: 33.55, category: '商科' },
  { uni: 'hkust', code: 'JS5331', name: '經濟及金融', formula: '最佳5科+加分', median: 48.19, lq: 46.50, category: '商科' },
  { uni: 'hkust', code: 'JS5332', name: '量化金融', formula: '最佳5科+加分', median: 58.13, lq: 56.06, category: '商科' },
  { uni: 'hkust', code: 'JS5814', name: '風險管理及商業智能', formula: '最佳5科+加分', median: 44.25, lq: 43.50, category: '商科' },
  { uni: 'hkust', code: 'JS5822', name: '可持續及綠色金融', formula: '最佳5科+加分', median: 37.88, lq: 37.13, category: '商科' },

  // ===== HKU =====
  { uni: 'hku', code: '6004', name: '建築學', formula: '最佳5科', median: 29, lq: 28, category: '建築' },
  { uni: 'hku', code: '6016', name: '測量學', formula: '最佳5科', median: 29, lq: 28, category: '建築' },
  { uni: 'hku', code: '6028', name: '園境學', formula: '最佳5科', median: 35, lq: 31, category: '建築' },
  { uni: 'hku', code: '6042', name: '城市研究', formula: '最佳5科', median: 29, lq: 27, category: '社科' },
  { uni: 'hku', code: '6054', name: '文學', formula: '2×英文+最佳4科', median: 35, lq: 34, category: '文科' },
  { uni: 'hku', code: '6274', name: '全球創意產業', formula: '2×英文+最佳4科', median: 33, lq: 32, category: '創意' },
  { uni: 'hku', code: '6286', name: '人文及數碼科技', formula: '2×英文+最佳4科', median: 37, lq: 35, category: '文科' },
  { uni: 'hku', code: '6793', name: '工商管理（商業分析）', formula: '1.5×英+1.5×數+最佳3科', median: 35, lq: 34, category: '商科' },
  { uni: 'hku', code: '6808', name: '工商管理（法學）及法學士', formula: '1.5×英+1.5×數+最佳4科', median: 46, lq: 45, category: '雙學位' },
  { uni: 'hku', code: '6846', name: '市場學分析與科技', formula: '1.5×英+1.5×數+最佳3科', median: 33, lq: 32, category: '商科' },
  { uni: 'hku', code: '6860', name: '資產管理及私人銀行金融', formula: '1.5×英+1.5×數+最佳4科', median: 47, lq: 46, category: '商科' },
  { uni: 'hku', code: '6884', name: '量化金融', formula: '1.5×英+1.25×數+1.25×M1/M2+最佳3科', median: 51, lq: 50, category: '商科' },
  { uni: 'hku', code: '6896', name: '國際商業及全球管理', formula: '1.5×英+1.5×數+最佳4科', median: 54, lq: 53, category: '商科' },
  { uni: 'hku', code: '6107', name: '牙科學', formula: '生物/化學×1.3+最佳5科', median: 48, lq: 47, category: '健康醫學' },
  { uni: 'hku', code: '6066', name: '語言教育（英文）', formula: '1.5×英文+最佳4科', median: 32, lq: 32, category: '教育' },
  { uni: 'hku', code: '6080', name: '語言教育（中文）', formula: '1.5×中文+最佳4科', median: 35, lq: 34, category: '教育' },
  { uni: 'hku', code: '6092', name: '幼兒教育及特殊教育', formula: '1.5×英文+最佳4科', median: 27, lq: 26, category: '教育' },
  { uni: 'hku', code: '6119', name: '教育學及理學', formula: '英文+1.5×數+1.5×理科+最佳2科', median: 44, lq: 43, category: '教育' },
  { uni: 'hku', code: '6157', name: '言語病理學', formula: '最佳5科', median: 34, lq: 34, category: '健康醫學' },
  { uni: 'hku', code: '6353', name: '土木工程', formula: '英文+數學+最佳3科', median: 28, lq: 27, category: '工程' },
  { uni: 'hku', code: '6377', name: '工程及人工智能工程碩士', formula: '英文+數學+最佳3科', median: 33, lq: 31, category: '工程' },
  { uni: 'hku', code: '6937', name: '環球工程及商業', formula: '英文+數學+最佳3科', median: 32, lq: 30, category: '工程' },
  { uni: 'hku', code: '6987', name: '電腦/電機/電子工程', formula: '英文+數學+最佳3科', median: 29, lq: 28, category: '工程' },
  { uni: 'hku', code: '6078', name: '文學士及法學士', formula: '英文+最佳5科', median: 38, lq: 36, category: '雙學位' },
  { uni: 'hku', code: '6406', name: '法學士', formula: '英文+最佳5科', median: 35, lq: 35, category: '法學' },
  { uni: 'hku', code: '6250', name: '全球健康及發展', formula: '最佳5科', median: 29, lq: 28, category: '健康醫學' },
  { uni: 'hku', code: '6418', name: '護理學（領袖訓練）', formula: '最佳5科+0.5×第6科', median: 37, lq: 36, category: '健康醫學' },
  { uni: 'hku', code: '6456', name: '內外全科醫學士', formula: '最佳6科', median: 44, lq: 42, category: '健康醫學' },
  { uni: 'hku', code: '6468', name: '護理學', formula: '最佳5科+0.5×第6科', median: 27, lq: 26, category: '健康醫學' },
  { uni: 'hku', code: '6482', name: '中醫學', formula: '最佳5科+0.5×第6科', median: 33, lq: 31, category: '健康醫學' },
  { uni: 'hku', code: '6494', name: '藥劑學', formula: '最佳6科', median: 39, lq: 38, category: '健康醫學' },
  { uni: 'hku', code: '6949', name: '生物醫學科學', formula: '最佳6科', median: 40, lq: 39, category: '健康醫學' },
  { uni: 'hku', code: '6688', name: '科學專修', formula: '英文+數學+最佳2科+加權科目', median: 34, lq: 32, category: '理科' },
  { uni: 'hku', code: '6858', name: '理科及法學士', formula: '2×英文+2×數/M1/M2+2×理科+最佳3科', median: 54, lq: 50, category: '雙學位' },
  { uni: 'hku', code: '6901', name: '理學', formula: '英文+1.5×數+1.5×理科+加權科目', median: 37, lq: 36, category: '理科' },
  { uni: 'hku', code: '6705', name: '心理學', formula: '最佳5科', median: 31, lq: 29, category: '社科' },
  { uni: 'hku', code: '6717', name: '社會科學', formula: '最佳5科', median: 31, lq: 29, category: '社科' },
  { uni: 'hku', code: '6731', name: '社會工作', formula: '最佳5科', median: 28, lq: 26, category: '社科' },
  { uni: 'hku', code: '6810', name: '社會科學（政府及法學）及法學士', formula: '最佳6科', median: 37, lq: 36, category: '雙學位' },
  { uni: 'hku', code: '6822', name: '新聞學、媒體及人工智能', formula: '1.5×英文+最佳4科', median: 32, lq: 31, category: '傳播' },
  { uni: 'hku', code: '6925', name: '生物醫學工程', formula: '英文+數學+最佳3科', median: 29, lq: 29, category: '工程' },
  { uni: 'hku', code: '6224', name: '應用人工智能', formula: '2×英文+2×數學+2×M1/M2+加權', median: 53, lq: 51, category: '電腦/數據' },
  { uni: 'hku', code: '6248', name: '金融科技', formula: '英文+數學+最佳3科', median: 34, lq: 32, category: '商科' },
  { uni: 'hku', code: '6729', name: '精算學', formula: '1.2×英文+1.2×數學+1.2×M1/M2+最佳2科', median: 35, lq: 35, category: '商科' },
  { uni: 'hku', code: '6779', name: '統計決策學', formula: '1.5×數學+最佳4科', median: 33, lq: 31, category: '理科' },
  { uni: 'hku', code: '6999', name: '計算及數據科學', formula: '英文+1.5×數學+加權+最佳科', median: 41, lq: 39, category: '電腦/數據' },
  { uni: 'hku', code: '6602', name: '創新及科技', formula: '2×英文+2×數學+加權科目', median: 55, lq: 52, category: '工程' },

  // ===== PolyU =====
  { uni: 'polyu', code: 'JS3150', name: '生物醫學工程', formula: '最佳5科', median: 218, lq: 213.5, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3320', name: '中國歷史與文化', formula: '最佳5科+第6科加分', median: 223, lq: 210, category: '文科' },
  { uni: 'polyu', code: 'JS3739', name: '土木工程', formula: '最佳5科', median: 216.5, lq: 205, category: '工程' },
  { uni: 'polyu', code: 'JS3006', name: '電腦及數學科學', formula: '最佳5科', median: 215, lq: 210, category: '電腦/數據' },
  { uni: 'polyu', code: 'JS3868', name: '計算學及人工智能', formula: '最佳5科', median: 230, lq: 215, category: '電腦/數據' },
  { uni: 'polyu', code: 'JS3004', name: '建築及環境', formula: '最佳5科+第6科加分', median: 184, lq: 181, category: '建築' },
  { uni: 'polyu', code: 'JS3223', name: '數據科學及人工智能', formula: '最佳5科', median: 220, lq: 211, category: '電腦/數據' },
  { uni: 'polyu', code: 'JS3569', name: '設計學', formula: '最佳5科', median: 178, lq: 190, category: '創意' },
  { uni: 'polyu', code: 'JS3170', name: '電機工程', formula: '最佳5科', median: 215, lq: 210, category: '工程' },
  { uni: 'polyu', code: 'JS3005', name: '工程學', formula: '最佳5科', median: 215, lq: 205, category: '工程' },
  { uni: 'polyu', code: 'JS3050', name: '時裝學', formula: '最佳5科+第6科加分', median: 177, lq: 164, category: '創意' },
  { uni: 'polyu', code: 'JS3255', name: '食品科學及營養學', formula: '最佳5科', median: 203, lq: 198.5, category: '理科' },
  { uni: 'polyu', code: 'JS3070', name: '環球商業及物流航運管理', formula: '最佳5科', median: 179, lq: 175, category: '商科' },
  { uni: 'polyu', code: 'JS3310', name: '酒店及旅遊管理', formula: '最佳5科', median: 166.5, lq: 163, category: '商科' },
  { uni: 'polyu', code: 'JS3007', name: '人文學', formula: '最佳5科+第6科加分', median: 185, lq: 179, category: '文科' },
  { uni: 'polyu', code: 'JS3180', name: '資訊及人工智能工程', formula: '最佳5科', median: 218, lq: 210, category: '工程' },
  { uni: 'polyu', code: 'JS3237', name: '智能供應鏈及工程管理', formula: '最佳5科', median: 195, lq: 193, category: '商科' },
  { uni: 'polyu', code: 'JS3337', name: '精神健康護理', formula: '最佳5科', median: 209, lq: 206, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3648', name: '護理學', formula: '最佳5科', median: 218, lq: 213.5, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3624', name: '職業治療', formula: '最佳5科', median: 278, lq: 279.5, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3290', name: '眼科視光學', formula: '最佳5科+第6科加分', median: 277.8, lq: 247.8, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3030', name: '物理學（AI/創新及創業）', formula: '最佳5科', median: 215, lq: 205, category: '理科' },
  { uni: 'polyu', code: 'JS3636', name: '物理治療', formula: '最佳5科', median: 320, lq: 320, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3236', name: '產品創新及智能製造工程', formula: '最佳5科', median: 195, lq: 193, category: '工程' },
  { uni: 'polyu', code: 'JS3612', name: '放射學', formula: '最佳5科+第6科加分', median: 339, lq: 328.5, category: '健康醫學' },
  { uni: 'polyu', code: 'JS3008', name: '科學學', formula: '最佳5科', median: 208, lq: 205, category: '理科' },
  { uni: 'polyu', code: 'JS3130', name: '空間數據科學及智慧城市', formula: '最佳5科', median: 206, lq: 203, category: '電腦/數據' },
  { uni: 'polyu', code: 'JS3241', name: '翻譯、語言學及言語治療', formula: '最佳5科+第6科加分', median: 189.5, lq: 188.6, category: '文科' },

  // ===== HKMU =====
  { uni: 'hkmud', code: 'JS9009', name: '社會科學（老年學/經濟/社會研究/政治）', formula: '最佳5科', median: 16, lq: 15, category: '社科' },
  { uni: 'hkmud', code: 'JS9010', name: '社會科學（心理學）', formula: '最佳5科', median: 16, lq: 14, category: '社科' },
  { uni: 'hkmud', code: 'JS9011', name: '中文（榮譽）', formula: '最佳5科', median: 22, lq: 21, category: '文科' },
  { uni: 'hkmud', code: 'JS9013', name: '語言研究及翻譯（榮譽）', formula: '最佳5科', median: 20, lq: 19, category: '文科' },
  { uni: 'hkmud', code: 'JS9016', name: '創意廣告及媒體設計（榮譽）', formula: '最佳5科', median: 20, lq: 18, category: '創意' },
  { uni: 'hkmud', code: 'JS9019', name: '英文語言及文化（榮譽）', formula: '最佳5科', median: 17, lq: 15, category: '文科' },
  { uni: 'hkmud', code: 'JS9220', name: '專業會計（榮譽）', formula: '最佳5科', median: 17, lq: 17, category: '商科' },
  { uni: 'hkmud', code: 'JS9230', name: '商業管理（榮譽）', formula: '最佳5科', median: 16, lq: 15, category: '商科' },
  { uni: 'hkmud', code: 'JS9240', name: '環球商業（榮譽）', formula: '最佳5科', median: 18, lq: 17, category: '商科' },
  { uni: 'hkmud', code: 'JS9262', name: '人力資源管理（榮譽）', formula: '最佳5科', median: 16, lq: 14, category: '商科' },
  { uni: 'hkmud', code: 'JS9266', name: '市場學（榮譽）', formula: '最佳5科', median: 16, lq: 15, category: '商科' },
  { uni: 'hkmud', code: 'JS9276', name: '房地產及測量（榮譽）', formula: '最佳5科', median: 17, lq: 16, category: '商科' },
  { uni: 'hkmud', code: 'JS9280', name: '應用心理學（榮譽）', formula: '最佳5科', median: 16, lq: 15, category: '社科' },
  { uni: 'hkmud', code: 'JS9291', name: '可持續旅遊及酒店管理（榮譽）', formula: '最佳5科', median: 16, lq: 15, category: '商科' },
  { uni: 'hkmud', code: 'JS9294', name: '體育及電子競技管理（榮譽）', formula: '最佳5科', median: 17, lq: 16, category: '商科' },
  { uni: 'hkmud', code: 'JS9540', name: '英文語言研究（榮譽）', formula: '最佳5科', median: 20, lq: 18, category: '文科' },
  { uni: 'hkmud', code: 'JS9550', name: '語言研究（榮譽，應用中文）', formula: '最佳5科', median: 22, lq: 19, category: '文科' },
  { uni: 'hkmud', code: 'JS9555', name: '語言研究（榮譽，應用劇場）', formula: '最佳5科', median: 23, lq: 22, category: '文科' },
  { uni: 'hkmud', code: 'JS9560', name: '教育（中文教學）及語言研究（榮譽）', formula: '最佳5科', median: 22, lq: 21, category: '教育' },
  { uni: 'hkmud', code: 'JS9580', name: '幼兒教育（領袖及特殊教育需要）', formula: '最佳5科', median: 16, lq: 14, category: '教育' },
  { uni: 'hkmud', code: 'JS9719', name: '網絡及電腦安全（榮譽）', formula: '最佳5科', median: 15, lq: 15, category: '電腦/數據' },
  { uni: 'hkmud', code: 'JS9720', name: '電子及電腦工程（榮譽）', formula: '最佳5科', median: 17, lq: 16, category: '工程' },
  { uni: 'hkmud', code: 'JS9731', name: '環境科學及綠色管理（榮譽）', formula: '最佳5科', median: 17, lq: 16, category: '理科' },
  { uni: 'hkmud', code: 'JS9732', name: '生物醫學科學及生物科技（榮譽）', formula: '最佳5科', median: 17, lq: 16, category: '理科' },
  { uni: 'hkmud', code: 'JS9733', name: '科學（STEAM）（榮譽）', formula: '最佳5科', median: 17, lq: 15, category: '理科' },
  { uni: 'hkmud', code: 'JS9776', name: '建築工程及管理（榮譽）', formula: '最佳5科', median: 19, lq: 17, category: '工程' },
]
